### ISSUE TITLE
Circle fan tracking

### ISSUE THREAD

**Issue by jonas-chow** [jonas-chow/umabot#1]
- [ ] Add circle to server
- [ ] Add user to circle -- discord handle, fan count
- [ ] Remove user to circle -- make sure to keep the order
- [ ] Update fan count
